version: "3.3"
services:
  star-tides:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      FLASK_DEBUG: 1
    restart: always
    volumes:
      - ./:/app
    depends_on:
      - db
    ports:
      - 5000:5000

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports: ["5432:5432"]
    expose: ['5432']

  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: star_tides
    ports:
      - 27017:27017
    volumes:
      - db-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
  migrate:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    depends_on:
      - db
    command: sh -c "cd /app/star_tides/services/sql/database/migrations && alembic upgrade head"

volumes:
  db-data:
