version: "3.3"
services:
  star-tides:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      FLASK_DEBUG: 0
    restart: always
    volumes:
      - ./:/app
    networks:
      my-network:
        aliases:
          - flask-app
    depends_on:
      - db
    ports:
      - 5000:5000
  nginx:
    image: nginx:latest
    ports:
      # - 443:443
      - 80:80
    # volumes:
    #   - ./infra/local/nginx.conf:/etc/nginx/conf.d/default.conf
    #   - ./infra/local/nginx.crt:/etc/ssl/certs/nginx-selfsigned.crt
    #   - ./infra/local/selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
    networks:
      - my-network
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
networks:
  my-network: