version: "3.3"
services:
  star-tides:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      FLASK_DEBUG: 1
    restart: always
    volumes:
      - ./:/app
    depends_on:
      - db
    ports:
      - 5000:5000

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports: ["5432:5432"]
    expose: ['5432']
  migrate:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    depends_on:
      - db
    command: sh -c "wait 1000 && cd /app/star_tides/services/sql/database/migrations && alembic upgrade head"
